---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# RobinHood

This is package is designed to help you execute trading programs in R. It was copied from 'https://github.com/JestonBlu/RobinHood.git/' to add functionality for IRA accounts, easier authentication, and dollar based trading. 

## Installation

This will not be submitted to CRAN. Install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("exploringfinance/RobinHood")
```
## Account Features
- [x] Account data
- [x] Add and remove investments on your watchlist
- [x] Execute ACH transfers
- [x] MFA enabled
- [x] Use of IRA Accounts

## Equity Features
- [x] Get current holdings
- [x] Access investment statistics and quotes
- [x] Place and cancel orders (notional and shares)
- [x] Get order status
- [x] Get price history
- [x] Get order history
- [x] Get market open/close hours
- [x] Search investments by popular tag
- [x] Calculate historical account balance
- [x] Get options market data
- [x] Get options positions
- [x] Get analyst ratings

## Crypto Features
- [x] Get current holdings
- [x] Get order history
- [x] Get quotes
- [x] Place and cancel orders
- [x] Get order status

**Note:** A key difference between the CRAN version and the Github version is that the API functions are exported and available to call directly. This is intended primarily to help with development and bug fixes. In the CRAN version, all API functions are not exported and instead are called behind the scenes.



